// Zimbabwe Districts
export const zimbabweDistricts = [
  // Harare Province
  "Harare", "Chitungwiza", "Epworth",
  // Bulawayo Province
  "Bulawayo",
  // Manicaland
  "Mutare", "Rusape", "Chipinge", "Nyanga", "Chimanimani",
  // Mashonaland Central
  "Bindura", "Guruve", "Mount Darwin", "Mazowe",
  // Mashonaland East
  "Marondera", "Murehwa", "Mutoko", "Mudzi", "Goromonzi",
  // Mashonaland West
  "Chinhoyi", "Kariba", "Hurungwe", "Makonde", "Chegutu",
  // Masvingo
  "Masvingo", "Chivi", "Gutu", "Zaka", "Bikita", "Mwenezi",
  // Matabeleland North
  "Hwange", "Binga", "Victoria Falls", "Lupane",
  // Matabeleland South
  "Gwanda", "Beitbridge", "Plumtree", "Insiza",
  // Midlands
  "Gweru", "Kwekwe", "Gokwe", "Shurugwi", "Zvishavane"
];

// Produce Categories
export const categories = [
  { id: "vegetables", name: "Vegetables", icon: "🥬" },
  { id: "fruits", name: "Fruits", icon: "🍎" },
  { id: "grains", name: "Grains", icon: "🌾" },
  { id: "livestock", name: "Livestock", icon: "🐄" },
  { id: "poultry", name: "Poultry", icon: "🐔" },
  { id: "dairy", name: "Dairy", icon: "🥛" },
];

// Farmers
export const farmers = [
  {
    id: "1",
    name: "Tendai Moyo",
    location: "Harare",
    crops: ["Maize", "Tomatoes"],
    rating: 4.8,
    totalListings: 12,
    memberSince: "2023-01-15",
    verified: true,
    phone: "+263 77 123 4567",
    bio: "Experienced maize and vegetable farmer with 15 years in organic farming.",
  },
  {
    id: "2",
    name: "Chipo Ncube",
    location: "Bulawayo",
    crops: ["Onions", "Butternut", "Tomatoes"],
    rating: 4.9,
    totalListings: 18,
    memberSince: "2022-08-20",
    verified: true,
    phone: "+263 71 234 5678",
    bio: "Specializing in high-quality vegetables for urban markets.",
  },
  {
    id: "3",
    name: "Tapiwa Mutasa",
    location: "Mutare",
    crops: ["Bananas", "Avocados"],
    rating: 4.7,
    totalListings: 8,
    memberSince: "2023-03-10",
    verified: true,
    phone: "+263 78 345 6789",
    bio: "Fruit farmer focusing on bananas and avocados in Eastern Highlands.",
  },
  {
    id: "4",
    name: "Rudo Sibanda",
    location: "Gweru",
    crops: ["Poultry", "Eggs"],
    rating: 4.9,
    totalListings: 15,
    memberSince: "2022-11-05",
    verified: true,
    phone: "+263 77 456 7890",
    bio: "Free-range poultry and egg producer with focus on quality and animal welfare.",
  },
  {
    id: "5",
    name: "Farai Ndlovu",
    location: "Masvingo",
    crops: ["Sorghum", "Millet"],
    rating: 4.6,
    totalListings: 6,
    memberSince: "2023-02-18",
    verified: false,
    phone: "+263 71 567 8901",
    bio: "Traditional grains farmer promoting local food security.",
  },
  {
    id: "6",
    name: "Nyasha Chidzonga",
    location: "Zvishavane",
    crops: ["Groundnuts"],
    rating: 4.8,
    totalListings: 10,
    memberSince: "2022-07-12",
    verified: true,
    phone: "+263 78 678 9012",
    bio: "Groundnut specialist with sustainable farming practices.",
  },
  {
    id: "7",
    name: "Simba Dube",
    location: "Kadoma",
    crops: ["Livestock"],
    rating: 4.5,
    totalListings: 5,
    memberSince: "2023-04-22",
    verified: false,
    phone: "+263 77 789 0123",
    bio: "Livestock farmer specializing in goats and cattle.",
  },
  {
    id: "8",
    name: "Tatenda Gumbo",
    location: "Chinhoyi",
    crops: ["Tobacco"],
    rating: 4.7,
    totalListings: 4,
    memberSince: "2022-12-08",
    verified: true,
    phone: "+263 71 890 1234",
    bio: "Premium tobacco grower with export quality produce.",
  },
  {
    id: "9",
    name: "Tariro Banda",
    location: "Marondera",
    crops: ["Mixed Vegetables"],
    rating: 4.9,
    totalListings: 22,
    memberSince: "2022-05-15",
    verified: true,
    phone: "+263 78 901 2345",
    bio: "Diverse vegetable production for local and urban markets.",
  },
  {
    id: "10",
    name: "Rufaro Mlambo",
    location: "Gwanda",
    crops: ["Sweet Potatoes"],
    rating: 4.6,
    totalListings: 7,
    memberSince: "2023-01-30",
    verified: false,
    phone: "+263 77 012 3456",
    bio: "Sweet potato grower with focus on nutrition and food security.",
  },
];

// Produce Listings
export const produceListings = [
  {
    id: "1",
    farmerId: "1",
    category: "grains",
    produceName: "White Maize",
    variety: "SC403",
    quantity: 5,
    unit: "tonnes",
    pricePerUnit: 450,
    currency: "USD",
    negotiable: true,
    location: "Harare",
    district: "Harare",
    availableFrom: "2024-05-01",
    availableUntil: "2024-08-31",
    deliveryAvailable: true,
    description: "Premium white maize, ideal for milling. Grown organically without pesticides. Grade A quality.",
    images: ["maize-field-zimbabwe"],
    views: 145,
    inquiries: 12,
    status: "active",
    listedDate: "2024-04-15",
  },
  {
    id: "2",
    farmerId: "1",
    category: "grains",
    produceName: "Yellow Maize",
    variety: "SC513",
    quantity: 3,
    unit: "tonnes",
    pricePerUnit: 420,
    currency: "USD",
    negotiable: true,
    location: "Harare",
    district: "Harare",
    availableFrom: "2024-05-01",
    availableUntil: "2024-08-31",
    deliveryAvailable: true,
    description: "High-yield yellow maize suitable for livestock feed and industrial use.",
    images: ["african-agriculture-technology"],
    views: 98,
    inquiries: 8,
    status: "active",
    listedDate: "2024-04-15",
  },
  {
    id: "3",
    farmerId: "2",
    category: "vegetables",
    produceName: "Tomatoes",
    variety: "Roma",
    quantity: 500,
    unit: "kg",
    pricePerUnit: 180,
    currency: "USD",
    negotiable: false,
    location: "Bulawayo",
    district: "Bulawayo",
    availableFrom: "2024-04-20",
    availableUntil: "2024-06-30",
    deliveryAvailable: true,
    description: "Fresh Roma tomatoes, perfect for cooking and salads. Harvested daily for maximum freshness.",
    images: ["tomatoes-harvest"],
    views: 234,
    inquiries: 28,
    status: "active",
    listedDate: "2024-04-10",
  },
  {
    id: "4",
    farmerId: "2",
    category: "vegetables",
    produceName: "Red Onions",
    variety: "Red Creole",
    quantity: 800,
    unit: "kg",
    pricePerUnit: 220,
    currency: "USD",
    negotiable: true,
    location: "Bulawayo",
    district: "Bulawayo",
    availableFrom: "2024-04-25",
    availableUntil: "2024-09-30",
    deliveryAvailable: true,
    description: "Premium red onions with excellent storage quality. Suitable for retail and wholesale.",
    images: ["african-vegetables-market"],
    views: 187,
    inquiries: 15,
    status: "active",
    listedDate: "2024-04-12",
  },
  {
    id: "5",
    farmerId: "9",
    category: "vegetables",
    produceName: "Butternut Squash",
    variety: "Waltham",
    quantity: 600,
    unit: "kg",
    pricePerUnit: 150,
    currency: "USD",
    negotiable: true,
    location: "Marondera",
    district: "Marondera",
    availableFrom: "2024-04-18",
    availableUntil: "2024-07-31",
    deliveryAvailable: true,
    description: "Sweet and nutritious butternut squash. High demand for soups and baby food.",
    images: ["butternut-squash"],
    views: 276,
    inquiries: 32,
    status: "active",
    listedDate: "2024-04-08",
  },
  {
    id: "6",
    farmerId: "3",
    category: "fruits",
    produceName: "Bananas",
    variety: "Cavendish",
    quantity: 400,
    unit: "kg",
    pricePerUnit: 280,
    currency: "USD",
    negotiable: false,
    location: "Mutare",
    district: "Mutare",
    availableFrom: "2024-04-15",
    availableUntil: "2024-12-31",
    deliveryAvailable: false,
    description: "Sweet Cavendish bananas from the Eastern Highlands. Year-round production.",
    images: ["african-food-market"],
    views: 312,
    inquiries: 41,
    status: "active",
    listedDate: "2024-04-05",
  },
  {
    id: "7",
    farmerId: "3",
    category: "fruits",
    produceName: "Avocados",
    variety: "Hass",
    quantity: 200,
    unit: "kg",
    pricePerUnit: 450,
    currency: "USD",
    negotiable: true,
    location: "Mutare",
    district: "Mutare",
    availableFrom: "2024-04-20",
    availableUntil: "2024-08-31",
    deliveryAvailable: false,
    description: "Premium Hass avocados, creamy and delicious. Perfect for export and high-end markets.",
    images: ["zimbabwe-agriculture"],
    views: 198,
    inquiries: 22,
    status: "active",
    listedDate: "2024-04-11",
  },
  {
    id: "8",
    farmerId: "4",
    category: "poultry",
    produceName: "Free-Range Eggs",
    variety: "Mixed Breed",
    quantity: 1000,
    unit: "trays",
    pricePerUnit: 45,
    currency: "USD",
    negotiable: false,
    location: "Gweru",
    district: "Gweru",
    availableFrom: "2024-04-01",
    availableUntil: "2024-12-31",
    deliveryAvailable: true,
    description: "Fresh free-range eggs from happy hens. Daily collection ensures quality and freshness.",
    images: ["african-woman-farmer"],
    views: 445,
    inquiries: 67,
    status: "active",
    listedDate: "2024-04-01",
  },
  {
    id: "9",
    farmerId: "4",
    category: "poultry",
    produceName: "Broiler Chickens",
    variety: "Cobb 500",
    quantity: 50,
    unit: "birds (avg 2.5kg)",
    pricePerUnit: 300,
    currency: "USD",
    negotiable: true,
    location: "Gweru",
    district: "Gweru",
    availableFrom: "2024-05-05",
    availableUntil: "2024-05-20",
    deliveryAvailable: true,
    description: "Healthy broiler chickens ready for market. Fed on quality grain-based feed.",
    images: ["african-farmer"],
    views: 221,
    inquiries: 18,
    status: "active",
    listedDate: "2024-04-18",
  },
  {
    id: "10",
    farmerId: "5",
    category: "grains",
    produceName: "Sorghum",
    variety: "Red Sorghum",
    quantity: 2,
    unit: "tonnes",
    pricePerUnit: 380,
    currency: "USD",
    negotiable: true,
    location: "Masvingo",
    district: "Masvingo",
    availableFrom: "2024-05-10",
    availableUntil: "2024-10-31",
    deliveryAvailable: true,
    description: "Traditional red sorghum, drought-resistant and nutritious. Excellent for brewing and food.",
    images: ["zimbabwean-crops"],
    views: 134,
    inquiries: 9,
    status: "active",
    listedDate: "2024-04-20",
  },
  {
    id: "11",
    farmerId: "5",
    category: "grains",
    produceName: "Pearl Millet",
    variety: "Pearl Millet",
    quantity: 1.5,
    unit: "tonnes",
    pricePerUnit: 350,
    currency: "USD",
    negotiable: true,
    location: "Masvingo",
    district: "Masvingo",
    availableFrom: "2024-05-10",
    availableUntil: "2024-10-31",
    deliveryAvailable: true,
    description: "Nutritious pearl millet with high protein content. Ideal for traditional foods.",
    images: ["rural-zimbabwe"],
    views: 87,
    inquiries: 5,
    status: "active",
    listedDate: "2024-04-20",
  },
  {
    id: "12",
    farmerId: "6",
    category: "vegetables",
    produceName: "Groundnuts",
    variety: "Nyanda",
    quantity: 1,
    unit: "tonne",
    pricePerUnit: 520,
    currency: "USD",
    negotiable: true,
    location: "Zvishavane",
    district: "Zvishavane",
    availableFrom: "2024-05-01",
    availableUntil: "2024-11-30",
    deliveryAvailable: true,
    description: "High-quality shelled groundnuts. Excellent for peanut butter production and snacks.",
    images: ["farm-produce"],
    views: 167,
    inquiries: 14,
    status: "active",
    listedDate: "2024-04-16",
  },
  {
    id: "13",
    farmerId: "9",
    category: "vegetables",
    produceName: "Cabbage",
    variety: "Green Cabbage",
    quantity: 400,
    unit: "heads",
    pricePerUnit: 25,
    currency: "USD",
    negotiable: false,
    location: "Marondera",
    district: "Marondera",
    availableFrom: "2024-04-22",
    availableUntil: "2024-07-31",
    deliveryAvailable: true,
    description: "Fresh, crisp cabbage heads. Perfect for coleslaw, salads, and cooking.",
    images: ["african-vegetables-market"],
    views: 203,
    inquiries: 24,
    status: "active",
    listedDate: "2024-04-14",
  },
  {
    id: "14",
    farmerId: "9",
    category: "vegetables",
    produceName: "Spinach",
    variety: "African Spinach",
    quantity: 100,
    unit: "kg",
    pricePerUnit: 120,
    currency: "USD",
    negotiable: false,
    location: "Marondera",
    district: "Marondera",
    availableFrom: "2024-04-20",
    availableUntil: "2024-06-30",
    deliveryAvailable: true,
    description: "Fresh African spinach, harvested daily. Rich in nutrients and flavor.",
    images: ["zimbabwe-farm"],
    views: 156,
    inquiries: 19,
    status: "active",
    listedDate: "2024-04-13",
  },
  {
    id: "15",
    farmerId: "10",
    category: "vegetables",
    produceName: "Sweet Potatoes",
    variety: "Orange Flesh",
    quantity: 1,
    unit: "tonne",
    pricePerUnit: 180,
    currency: "USD",
    negotiable: true,
    location: "Gwanda",
    district: "Gwanda",
    availableFrom: "2024-05-05",
    availableUntil: "2024-09-30",
    deliveryAvailable: true,
    description: "Nutritious orange-fleshed sweet potatoes. High in vitamin A and perfect for health programs.",
    images: ["zimbabwe-agriculture"],
    views: 189,
    inquiries: 16,
    status: "active",
    listedDate: "2024-04-17",
  },
  {
    id: "16",
    farmerId: "9",
    category: "vegetables",
    produceName: "Green Peppers",
    variety: "Bell Pepper",
    quantity: 300,
    unit: "kg",
    pricePerUnit: 250,
    currency: "USD",
    negotiable: true,
    location: "Marondera",
    district: "Marondera",
    availableFrom: "2024-04-25",
    availableUntil: "2024-07-31",
    deliveryAvailable: true,
    description: "Fresh green bell peppers. Great for salads, stir-fries, and grilling.",
    images: ["farm-produce"],
    views: 178,
    inquiries: 21,
    status: "active",
    listedDate: "2024-04-15",
  },
  {
    id: "17",
    farmerId: "9",
    category: "vegetables",
    produceName: "Carrots",
    variety: "Nantes",
    quantity: 500,
    unit: "kg",
    pricePerUnit: 200,
    currency: "USD",
    negotiable: false,
    location: "Marondera",
    district: "Marondera",
    availableFrom: "2024-04-28",
    availableUntil: "2024-08-31",
    deliveryAvailable: true,
    description: "Sweet and crunchy Nantes carrots. Perfect for juicing, cooking, and snacking.",
    images: ["african-food-market"],
    views: 192,
    inquiries: 17,
    status: "active",
    listedDate: "2024-04-16",
  },
  {
    id: "18",
    farmerId: "9",
    category: "vegetables",
    produceName: "Cucumbers",
    variety: "English Cucumber",
    quantity: 200,
    unit: "kg",
    pricePerUnit: 150,
    currency: "USD",
    negotiable: false,
    location: "Marondera",
    district: "Marondera",
    availableFrom: "2024-04-22",
    availableUntil: "2024-07-31",
    deliveryAvailable: true,
    description: "Fresh, crisp English cucumbers. Ideal for salads and sandwiches.",
    images: ["zimbabwe-farm"],
    views: 143,
    inquiries: 13,
    status: "active",
    listedDate: "2024-04-14",
  },
];

// Market Prices
export const marketPrices = [
  { produce: "White Maize", currentPrice: 450, change: 12, min: 420, max: 480, unit: "kg", trend: "up" },
  { produce: "Tomatoes", currentPrice: 175, change: -5, min: 150, max: 200, unit: "kg", trend: "down" },
  { produce: "Red Onions", currentPrice: 225, change: 8, min: 200, max: 250, unit: "kg", trend: "up" },
  { produce: "Butternut", currentPrice: 150, change: 0, min: 130, max: 170, unit: "kg", trend: "stable" },
  { produce: "Potatoes", currentPrice: 200, change: 3, min: 180, max: 220, unit: "kg", trend: "up" },
  { produce: "Cabbage", currentPrice: 25, change: 0, min: 20, max: 30, unit: "head", trend: "stable" },
  { produce: "Eggs", currentPrice: 45, change: 2, min: 40, max: 50, unit: "tray", trend: "up" },
  { produce: "Avocados", currentPrice: 450, change: 5, min: 400, max: 500, unit: "kg", trend: "up" },
  { produce: "Bananas", currentPrice: 280, change: -2, min: 250, max: 300, unit: "kg", trend: "down" },
  { produce: "Sweet Potatoes", currentPrice: 180, change: 4, min: 160, max: 200, unit: "kg", trend: "up" },
];

// Buyers
export const buyers = [
  {
    id: "b1",
    name: "Chipo's Restaurant",
    type: "Restaurant",
    location: "Harare",
    phone: "+263 24 123 4567",
  },
  {
    id: "b2",
    name: "Fresh Market Retailers",
    type: "Retail Chain",
    location: "Bulawayo",
    phone: "+263 29 234 5678",
  },
  {
    id: "b3",
    name: "Green Grocer Stores",
    type: "Small Retailer",
    location: "Mutare",
    phone: "+263 20 345 6789",
  },
  {
    id: "b4",
    name: "School Feeding Program",
    type: "Institution",
    location: "National",
    phone: "+263 24 456 7890",
  },
  {
    id: "b5",
    name: "Sarah Khumalo",
    type: "Individual",
    location: "Harare",
    phone: "+263 77 567 8901",
  },
];

// Helper Functions
export function getFarmerById(id: string) {
  return farmers.find(f => f.id === id);
}

export function getListingById(id: string) {
  return produceListings.find(l => l.id === id);
}

export function getListingsByFarmer(farmerId: string) {
  return produceListings.filter(l => l.farmerId === farmerId && l.status === "active");
}

export function getListingsByCategory(category: string) {
  return produceListings.filter(l => l.category === category && l.status === "active");
}
